### ISSUE TITLE
onClick에 API 통신, navigate 동시할 경우 비동기 처리 해결

### ISSUE THREAD

**Issue by haileyham** [fe5-team6-project/withSix#120]
**📢 To-Do**
**onClick에 API 통신과 navigate 동시 처리할 경우 비동기 처리 필요**
- [x]  모임등록 페이지 > 모임리스트 페이지
- [x] 모임수정 페이지 > 모임상세 페이지
- [x] 모임삭제 > 모임리스트 페이지

**✏ How to & Then**
- onClick에 async, API 통신 함수에 await 
```
//예시
onClick={async () => { await sendTogether(); navigate(`/together/${accoutname}`); }
```

**🌱 MEMO**
